apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service # Name of your service
spec:
  selector:
    app: nextjs-app # Selector matches pods with this label (same as deployment)
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on (e.g., standard HTTP port)
      targetPort: 3000 # The port on the container to which the service forwards traffic
  type:
    LoadBalancer # Type of service:
    # - LoadBalancer: For cloud environments (creates an external IP).
    # - NodePort: For Minikube/local clusters to expose on a host port.
    # - ClusterIP: Only accessible within the Kubernetes cluster.
    # Choose NodePort for local Minikube testing if LoadBalancer doesn't work.
